### ISSUE TITLE
Calculate balances of users

### ISSUE THREAD

**Issue by casudo** [casudo/Kickbase-Insights#12]
Add a function to calculate the balances of the users in the league without the daily login bonus

**Comment by wiese1979** [comment]
Hi Casudo,

cool danke für das neue Feature. Leider funktioniert es bei mir immer noch nicht. Habe dir mal meinen Docker Befehl und die Log file angehangen. Immer noch kommt Seite in erreichbar bei http://localhost: 8049

Grüße
Wiese79

docker run -d \
    --name=kickbase_insights \
    --restart=unless-stopped \
    -p 3000:3000 -p 8049:5000 \
    -e [KB_MAIL=xxx \
    -e KB_PASSWORD=xxx \
    -e DISCORD_WEBHOOK=xxx \
    -e WATCHPACK_POLLING=true \
    -e TZ=Europe/Berlin \
    [ghcr.io/casudo/kickbase-insights:latest](http://ghcr.io/casudo/kickbase-insights:latest
![thumbnail_Bild 20 07 24 um 17 45](https://github.com/user-attachments/assets/c8fbe50e-f151-47c3-afa2-52a1ccb73fcb)

**Comment by casudo** [comment]
Hi @wiese1979 

das sieht alles korrekt aus. ;)

Warte bis in den Logs angezeigt wird, dass der Webserver gestartet wurde. In dem Screenshot ist das noch nicht der Fall.

Sollte es weitere Probleme geben, öffne bitte ein separates Issue.

LG
Casudo

**Comment by casudo** [comment]
Feature will be added soon.
