### ISSUE TITLE
/user/login endpoint throwing 404

### ISSUE THREAD

**Issue by casudo** [casudo/Kickbase-Insights#20]
It seems like the login endpoint has moved.

**Comment by casudo** [comment]
More to this:
https://github.com/phenze/kickbase-calculator/issues/5
https://github.com/kevinskyba/kickbase-api-doc/issues/3

**Comment by casudo** [comment]
Issue will be fixed in #21

**Comment by t3mr0i** [comment]
https://github.com/t3mr0i/Kickbase-API

I have documented all endpoints here.
