### ISSUE TITLE
Update API to v4

### ISSUE THREAD

**Issue by casudo** [casudo/Kickbase-Insights#21]
Kickbase deprecated all API endpoints prior to v4 and therefore added a lot of new ones in v4.

In typical Kickbase style, they couldn't name the response parameters in human readable text but rather in egypt hyroglyphs...

**Comment by phenze** [comment]
Yeah that is really annoying. If you need any help maybe my changes can help. Workes some hours on it yesterday.

Take a look here: https://github.com/phenze/kickbase-calculator/pull/6

**Comment by CRLgitrep** [comment]
I've added some endpoints I found to be working there:
https://github.com/phenze/kickbase-calculator/pull/6

**Comment by CRLgitrep** [comment]
Could you share your endpoints please? I haven't found any others besides the one I posted above. :(

**Comment by casudo** [comment]
90% done. Only gift collection and player live points needs to be updated to v4.
