### ISSUE TITLE
Wie benutze ich das Tool?

### ISSUE THREAD

**Issue by techniggoIG** [casudo/Kickbase-Insights#22]
Servus, hab bis jetzt immer noch den Webclient von FabiFischer benutzt bis vor 2 Tagen und konnte mich nicht mehr einloggen.
Hab jetzt ein wenig gesucht und bin hier gelandet. Könnte mir evtl. jemand weiterhelfen wie ich euer Tool zum laufen bekomm? :)

Grüße

**Comment by casudo** [comment]
Hi, Kickbase hat vor ein paar Tagen eine neue API Version eingeführt und alle vorherigen deaktiviert - daher funktioniert das Tool momentan nicht.

**Comment by techniggoIG** [comment]
Ja glaube nur das Kickbase+ nicht mehr updated wird, das letzte war im März 2023. Manche Funktionen waren ja zuvor schon verbugt seitdem KB auf die neue Version geupdatet hat dieses Jahr. War dennoch die beste Wahl wenn man nach einer guten Webapp gesucht hat. Scheint mir hier ja ziemlich ähnlich aufgebaut zu sein. Hab ewig gesucht die letzten Tage und es gibt keine alternativen sonst wo ich alles am PC selbst machen kann :/

**Comment by casudo** [comment]
Kickbase-Insights wurde gerade auf v2.4.0 geupdated. Ob Kickbase+ jemals geupdated wird, kann ich nicht sagen. 

Da dieses Projekt wieder funktionsfähig ist, werde ich das Issue schließen. Solltest du nach Probleme/Fragen haben, öffne einfach ein neues Issue oder schick mir eine Mail. :)
