### ISSUE TITLE
Deployment 

### ISSUE THREAD

**Issue by sirhc1893** [casudo/Kickbase-Insights#24]
Hi, is there an easy way for non devs to deploy your applicationen on a webspace? Would be nice to get some hints - thanks a lot!

**Comment by casudo** [comment]
As long as you have access to underlying server and can install Docker, you're fine to set everything up. 
If you rented a classic webspace for your own website, not a whole VPS, you cannot use it as of now.

I'll maybe add a website for this myself so users just need to login through their credentials - but this is planned as of now.

**Comment by casudo** [comment]
Not planned in the near future, but definitely on the roadmap.
I hope I could help you. If you have more questions, just re-open this issue, create a new one or mail me.
